// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using currency_exchange_calculator.Data;

#nullable disable

namespace currency_exchange_calculator.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240916091113_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("currency_exchange_calculator.Data.CurrencyConversion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("ConversionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("ConvertedAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("FromCurrency")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ToCurrency")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CurrencyConversions");
                });
#pragma warning restore 612, 618
        }
    }
}
